apiVersion: apps/v1
kind: Deployment
metadata:
  name: mgmt_api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mgmt_api
  template:
    metadata:
      labels:
        app: mgmt_api
    spec:
      containers:
      - name: mgmt_api
        image: quantotto/api_base:2.12.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 5000
        env:
        - name: CONFIG_API_URL
          value: http://config_api:5000/v1
        - name: FERNET_KEY
          value: ${FERNET_KEY}
        - name: API_PACKAGE
          value: "quantotto.mgmt_api"
        - name: REDIS_URL
          value: "redis://redis:6379"
        - name: BASE_DATA_PATH
          value: /training
        - name: LICENSE_PUBLIC_KEY_PATH
          value: ./license_public_key.pem
        - name: PACKAGES_FOLDER
          value: /packages
        - name: HYDRA_API_URL
          value: HYDRA_API_URL
        - name: HYDRA_PUBLIC_URL
          value: ${HYDRA_INTERNAL_PUBLIC_URL}
        - name: HYDRA_CONFIG_CLIENT_ID
          value: ${HYDRA_CONFIG_CLIENT_ID}
        - name: HYDRA_CONFIG_CLIENT_SECRET
          value: ${HYDRA_CONFIG_CLIENT_SECRET}
        - name: OAUTHLIB_INSECURE_TRANSPORT
          value: "yes"
        volumeMounts:
        - name: training-data
          mountPath: /training
        - name: packages
          mountPath: /packages
        - name: public-key-pem
          mountPath: /opt/quantotto/license_public_key.pem
      volumes:
      - name: training-data
        hostPath:
          path: /surveillancedata/training
      - name: packages
        hostPath:
          path: /surveillancedata/packages
      - name: public-key-pem
        hostPath:
          path: /surveillancedata/license_public_key.pem
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
