apiVersion: v1
kind: Service
metadata:
  name: mgmt_api
  labels:
    app: mgmt_api
spec:
  selector:
    app: mgmt_api
  ports:
  - name: "mgmtapi"
    port: 5000
    targetPort: 5000
status:
  loadBalancer: {}
