apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdb
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: qdb
  template:
    metadata:
      labels:
        app: qdb
    spec:
      volumes:
        - name: {{ .Values.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.volume.pvcName }}
      containers:
      - name: qdb
        image: "{{ .Values.image.repository }}/db:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        resources:
{{ toYaml .Values.resources | indent 10 }}
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secretName }}
              key: user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secretName }}
              key: password
        volumeMounts:
        - name: {{ .Values.volume.name }}
          mountPath: /var/lib/postgresql/data
          readOnly: false
      restartPolicy: {{ default "Always" .Values.restartPolicy | quote }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret | quote }}
