environments:
  default:
    values:
    - qtoconfig.yaml

repositories:
  - name: stable
    url: https://charts.helm.sh/stable
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: ory
    url: https://k8s.ory.sh/helm/charts
  - name: influxdata
    url: https://helm.influxdata.com/
  - name: openldap
    url: https://jp-gouin.github.io/helm-openldap/

releases:
  - name: config
    namespace: quantotto
    chart: ./charts/config
    values:
      - ./values/config.yaml.gotmpl

  - name: volumes
    namespace: quantotto
    chart: ./charts/volumes
    values:
      - ./values/volumes.yaml.gotmpl

  - name: qdb
    namespace: quantotto
    chart: ./charts/qdb
    values:
      - ./values/qdb.yaml.gotmpl
    needs:
      - quantotto/config
      - quantotto/volumes

  - name: openldap
    namespace: quantotto
    chart: openldap/openldap
    version: 2.0.4
    values:
      - ./values/openldap.yaml.gotmpl

  - name: hydra
    namespace: quantotto
    chart: ory/hydra
    version: 0.5.0
    values:
      - ./values/hydra.yaml.gotmpl
    needs:
      - quantotto/config
      - quantotto/qdb

  - name: config-api
    namespace: quantotto
    chart: ./charts/config_api
    values:
      - ./values/config_api.yaml.gotmpl
    needs:
      - quantotto/qdb
      - quantotto/hydra

  - name: influxdb
    namespace: quantotto
    chart: influxdata/influxdb
    version: 4.8.10
    values:
      - ./values/influxdb.yaml
    needs:
      - quantotto/config-api

  - name: mongodb
    namespace: quantotto
    chart: bitnami/mongodb
    version: 10.3.3
    values:
      - ./values/mongodb.yaml.gotmpl
    needs:
      - quantotto/config-api

  - name: rabbitmq
    namespace: quantotto
    chart: bitnami/rabbitmq
    version: 8.6.1
    values:
      - ./values/rabbitmq.yaml.gotmpl
    needs:
      - quantotto/config-api

  - name: redis
    namespace: quantotto
    chart: bitnami/redis
    version: 12.2.4
    values:
      - ./values/redis.yaml.gotmpl
    needs:
      - quantotto/config-api

  - name: neo4j
    namespace: quantotto
    chart: ./charts/neo4j
    values:
      - ./values/neo4j.yaml.gotmpl
    needs:
      - quantotto/config-api

  - name: auth-api
    namespace: quantotto
    chart: ./charts/app_api
    values:
      - ./values/auth_api.yaml.gotmpl
    needs:
      - quantotto/config-api

  - name: data-api
    namespace: quantotto
    chart: ./charts/app_api
    values:
      - ./values/data_api.yaml.gotmpl
    needs:
      - quantotto/config-api

  - name: management-api
    namespace: quantotto
    chart: ./charts/app_api
    values:
      - ./values/management_api.yaml.gotmpl
    needs:
      - quantotto/config-api

  - name: faces-archive-api
    namespace: quantotto
    chart: ./charts/app_api
    values:
      - ./values/faces_archive_api.yaml.gotmpl
    needs:
      - quantotto/config-api

  - name: ftp
    namespace: quantotto
    chart: ./charts/ftp
    values:
      - ./values/ftp.yaml.gotmpl
    needs:
      - quantotto/config-api

  - name: h5serv
    namespace: quantotto
    chart: ./charts/h5serv
    values:
      - ./values/h5serv.yaml.gotmpl
    needs:
      - quantotto/config-api

  - name: nginx
    namespace: quantotto
    chart: ./charts/nginx
    values:
      - ./values/nginx.yaml.gotmpl
    needs:
      - quantotto/config-api
      - quantotto/openldap
      - quantotto/hydra
