apiVersion: apps/v1
kind: Deployment
metadata:
  name: training_scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: training_scheduler
  template:
    metadata:
      labels:
        app: training_scheduler
    spec:
      containers:
      - name: training_scheduler
        image: quantotto/training_scheduler:2.12.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        env:
        - name: CONFIG_API_URL
          value: http://config_api:5000/v1
        - name: MGMT_API_URL
          value: http://mgmt_api:5000/v1
        - name: FERNET_KEY
          value: ${FERNET_KEY}
        - name: HYDRA_API_URL
          value: ${HYDRA_API_URL}
        - name: HYDRA_PUBLIC_URL
          value: ${HYDRA_INTERNAL_PUBLIC_URL}
        - name: HYDRA_CONFIG_CLIENT_ID
          value: ${HYDRA_CONFIG_CLIENT_ID}
        - name: HYDRA_CONFIG_CLIENT_SECRET
          value: ${HYDRA_CONFIG_CLIENT_SECRET}
        - name: HYDRA_CLIENT_ID
          value: ${CUSTOMER_ID}
        - name: HYDRA_CLIENT_SECRET
          value: ${HYDRA_CUSTOMER_CLIENT_SECRET}
        - name: OAUTHLIB_INSECURE_TRANSPORT
          value: "yes"
        - name: MODELS_FOLDER
          value: /training/models
        volumeMounts:
        - name: training-data
          mountPath: /training
      volumes:
      - name: training-data
        hostPath:
          path: /surveillancedata/training
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred

