{{ if and .Values.image.pullSecret.name .Values.image.pullSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.image.pullSecret.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: common
type: Opaque
data:
  FERNET_KEY: {{ .Values.keys.fernet | b64enc | quote }}
  HYDRA_CONFIG_CLIENT_SECRET: {{ .Values.configApi.clientSecret | b64enc | quote }}
  PRIVATE_KEY_PASSWORD: {{ .Values.keys.privateKeyPassword | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: privatekey
type: Opaque
data:
  private.key: |
    {{ .Values.keys.privateKey | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: certs
type: kubernetes.io/tls
data:
  tls.crt: |
    {{ .Values.cert.fullChain | b64enc }}
  tls.key: |
    {{ .Values.cert.privateKey | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: qdb
type: Opaque
data:
  user: {{ .Values.qdb.user | b64enc | quote }}
  password: {{ .Values.qdb.password | b64enc | quote }}

