apiVersion: v1
kind: Service
metadata:
  name: hydra
  labels:
    app: hydra
spec:
  type: LoadBalancer
  ports:
    - port: 4445
      targetPort: 4445
      protocol: TCP
      name: http-admin
    - port: 4444
      targetPort: 4444
      protocol: TCP
      name: http-public
  selector:
    app: hydra
