apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftp
    spec:
      containers:
      - image: quantotto/ftp:${QUANTOTTO_VERSION_TAG}
        name: ftp
        ports:
        - containerPort: 21
        - containerPort: 20
        - containerPort: 30000
        - containerPort: 30001
        - containerPort: 30002
        - containerPort: 30003
        - containerPort: 30004
        - containerPort: 30005
        - containerPort: 30006
        - containerPort: 30007
        - containerPort: 30008
        - containerPort: 30009
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        env:
        - name: FTP_ROOT
          value: "/ftp_root"
        - name: MASQUERADE_ADDRESS
          value: ${FTP_MASQUERADE_ADDRESS}
        - name: FRAME_PORTAL
          value: wss://nginx:15000/portal_ws
        volumeMounts:
        - name: ftp-root
          mountPath: /ftp_root
      volumes:
      - name: ftp-root
        hostPath:
          path: /surveillancedata/ftp-data
      restartPolicy: Always
