apiVersion: v1
kind: Service
metadata:
  name: qdb
  labels:
    app: qdb
spec:
  type: LoadBalancer
  selector:
    app: qdb
  ports:
  - name: qdb
    port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.port }}
status:
  loadBalancer: {}
