{{ if and .Values.image.pullSecret.name .Values.image.pullSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.image.pullSecret.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: customer-secret
  annotations:
    helm.sh/hook: "pre-install"
    helm.sh/hook-delete-policy: "before-hook-creation"
type: Opaque
data:
  HYDRA_CUSTOMER_CLIENT_SECRET: {{ randAlphaNum 32 | nospace | b64enc | quote }}
  ADMIN_PASSWORD: {{ .Values.customer.admin.password | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: common
  annotations:
    helm.sh/hook: "pre-install"
    helm.sh/hook-delete-policy: "before-hook-creation"
type: Opaque
data:
  FERNET_KEY: {{ .Values.encryptionKeys.fernet | b64enc | quote }}
  HYDRA_CONFIG_CLIENT_SECRET: {{ .Values.encryptionKeys.configClientSecret | b64enc | quote }}
  PRIVATE_KEY_PASSWORD: {{ .Values.encryptionKeys.privateKeyPassword | b64enc | quote }}
  STATE_GLOBAL_TOKEN: {{ randAlphaNum 32 | nospace | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: private-key
type: Opaque
data:
  private.key: {{ .Values.encryptionKeys.privateKey | b64enc | quote }}
  public.key: {{ .Values.encryptionKeys.publicKey | b64enc | quote }}
