apiVersion: v1
kind: Service
metadata:
  name: qdb
  labels:
    app: qdb
spec:
  type: NodePort
  selector:
    app: qdb
  ports:
  - name: "postgres"
    port: 5432
    targetPort: 5432
    nodePort: 30432
status:
  loadBalancer: {}
