apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdb
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: qdb
  template:
    metadata:
      labels:
        app: qdb
    spec:
      containers:
      - name: qdb
        image: quantotto/db:2.12.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "quantotto"
        - name: POSTGRES_PASSWORD
          value: "ymanlabs!"
        volumeMounts:
        - name: qdb-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: qdb-data
        hostPath:
          path: /surveillancedata/postgres-data
      restartPolicy: Always
      nodeSelector:
        dbnode: "yes"
      imagePullSecrets:
      - name: regcred
