apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdb
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: qdb
  template:
    metadata:
      labels:
        app: qdb
    spec:
      containers:
      - name: qdb
        image: "{{ .Values.image.repository }}/db:{{ .Values.image.tag }}"
        resources:
{{ toYaml .Values.resources | indent 10 }}
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
        - name: POSTGRES_USER
          value: {{ .Values.qdb.user | quote }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "qdb.fullname" . }}
              key: qdb-password
        volumeMounts:
        - name: qdb-data
          mountPath: /var/lib/postgresql/data
          readOnly: false
      restartPolicy: {{ default "Always" .Values.restartPolicy | quote }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret | quote }}
  volumeClaimTemplates:
    - metadata:
        name: qdb-data
      {{- with .Values.persistence.annotations }}
        annotations:
        {{- range $key, $value := . }}
          {{ $key }}: {{ $value }}
        {{- end }}
      {{- end }}
      spec:
        accessModes:
        {{- range .Values.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
