apiVersion: v1
kind: Service
metadata:
  name: qdb
  labels:
    app: qdb
spec:
  type: NodePort
  selector:
    app: qdb
  ports:
  - name: "postgres"
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    nodePort: {{ .Values.service.nodePort }}
status:
  loadBalancer: {}
