---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-api
data:
  API_PACKAGE: {{ .Values.configApi.package | quote }}
  HYDRA_API_URL: {{ .Values.hydra.apiUrl | quote }}
  CONFIG_FILE: {{ .Values.configApi.configFile | quote }}
  OAUTHLIB_INSECURE_TRANSPORT: "yes"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-common
data:
  PORTAL_FQDN: {{ .Values.portalFqdn | quote }}
  HYDRA_API_URL: {{ .Values.hydra.apiUrl | quote }}
  HYDRA_PUBLIC_URL: {{ .Values.hydra.internalPublicUrl | quote }}
  CONFIG_API_URL: {{ .Values.configApi.url | quote }}
  HYDRA_CONFIG_CLIENT_ID: {{ .Values.configApi.clientId | quote }}
  OAUTHLIB_INSECURE_TRANSPORT: "yes"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-api
data:
  API_PACKAGE: {{ .Values.authApi.package | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mgmt-api
data:
  API_PACKAGE: {{ .Values.managementApi.package | quote }}
  REDIS_URL: {{ .Values.managementApi.redisUrl | quote }}
  BASE_DATA_PATH: {{ .Values.managementApi.baseDataPath | quote }}
  LICENSE_PUBLIC_KEY_PATH: {{ .Values.managementApi.licensePublicKeyPath | quote }}
  PACKAGES_FOLDER: {{ .Values.managementApi.packagesFolder | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mgmt-api-files
data:
  license_public_key.pem: |
{{ .Values.encryptionKeys.publicKey | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: data-api
data:
  API_PACKAGE: {{ .Values.dataApi.package | quote }}
  PRIVATE_KEY_PATH: {{ .Values.dataApi.privateKeyPath | quote }}
  MEDIA_SERVER_FQDN: {{ .Values.dataApi.mediaServerFqdn | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: faces-archive-api
data:
  API_PACKAGE: {{ .Values.facesArchiveApi.package | quote }}
  H5_SERV_ENDPOINT: {{ .Values.facesArchiveApi.h5servEndpoint | quote }}
  ARCHIVE_DOMAIN: {{ .Values.facesArchiveApi.archiveDomain | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-env
data:
  RABBITMQ_NODENAME: rabbitmq
  RABBITMQ_VM_MEMORY_HIGH_WATERMARK: "0.20"
