apiVersion: v1
kind: Service
metadata:
  name: hydra
  labels:
    app: hydra
spec:
  selector:
    app.kubernetes.io/name: hydra
  ports:
  - port: 4445
    targetPort: 4445
    name: hydra-admin
  - port: 4444
    targetPort: 4444
    name: hydra-public
status:
  loadBalancer: {}
