product:
  quantotto_version: 3.10.0
  server_fqdn: portal.example.com
  server_ip: 192.168.0.100
  management_port: 443
  frames_port: 15000
  internal_host_subnet: 192.168.0.0/24
  docker_subnet: 172.21.0.0/16
  retention_days: 3
  server_password: ""

k8s:
  cluster_domain: example.com
  namespace: quantotto
  storage_class: my-local-storage
  encrypt_secrets: "pgp:753CAD4D4B26B9C4C4A043C8CBECFF86FD2D91FC"

customers:
  - id: qto
    name: Quantotto
    admin_email: quantottoinc@example.com
    admin_login: quantotto
    admin_fname: Quan
    admin_mname: ""
    admin_lname: Totto
    admin_password: "quantott0"
    postinstall:
      sites: []
      scenarios:
        - group: group_name
          name: flow_name
          description: ""
          nodes:
            streams:
              - id: ""
                name: s_name
                description: stream_description
                device_uris:
                  - video://
                  - audio://
            classifiers:
              - id: ""
                name: c_name
                description: classifier_description
                plugin: ""
                params: {}
            triggers:
              - id: ""
                name: t_name
                description: trigger_description
                plugin: ""
                observables: []
                params: {}
            actions:
              - id: ""
                name: a_name
                description: action_description
                plugin: ""
                params: {}
          connections:
            - id: ""
              source_id: ""
              target_id: ""
              src_params: {}
              tar_params: {}
