apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.api.name | replace "_" "-" }}
  labels:
    app: {{ .Values.api.name | replace "_" "-" }}
    group: {{ .Values.api.group }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.api.name | replace "_" "-" }}
  template:
    metadata:
      labels:
        app: {{ .Values.api.name | replace "_" "-" }}
        group: {{ .Values.api.group }}
    spec:
      volumes:
      - name: myconfig-data
        secret:
          secretName: config-api-files
          items:
          - key: myconfig.yaml
            path: myconfig.yaml
      - name: full-myconfig-data
        secret:
          secretName: config-api-files
          items:
          - key: fullmyconfig.yaml
            path: fullmyconfig.yaml
      containers:
      - name: {{ .Values.api.name | replace "_" "-" }}
        image: "{{ .Values.image.repository }}/config_api:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        resources:
{{ toYaml .Values.api.resources | indent 10 }}
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: {{ .Values.api.name | replace "_" "-" }}
        - secretRef:
            name: common
        volumeMounts:
        - name: myconfig-data
          mountPath: /myconfig
      restartPolicy: Always
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret | quote }}
