apiVersion: v1
kind: Service
metadata:
  name: ftp
  labels:
    app: ftp
spec:
  type: LoadBalancer
  selector:
    app: ftp
  ports:
{{ toYaml .Values.ports | indent 4 }}
status:
  loadBalancer: {}
