apiVersion: v1
kind: Service
metadata:
  name: auth_api
  labels:
    app: auth_api
spec:
  selector:
    app: auth_api
  ports:
  - name: "authapi"
    port: 5000
    targetPort: 5000
status:
  loadBalancer: {}
