apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
  - name: "nginxqmc"
    port: 443
    targetPort: 15000
  - name: "nginxwss"
    port: 15001
    targetPort: 15001
status:
  loadBalancer: {}

