apiVersion: v1
kind: Service
metadata:
  name: portal
  labels:
    app: portal
spec:
  selector:
    app: portal
  ports:
  - name: "portal"
    port: 5000
    targetPort: 5000
status:
  loadBalancer: {}