apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal
  template:
    metadata:
      labels:
        app: portal
    spec:
      containers:
      - name: portal
        image: quantotto/portal:2.12.0
        resources: { }
        ports:
        - containerPort: 5000
        env:
        - name: CUSTOMER_ID
          value: ${CUSTOMER_ID}
        - name: ACTOR_SYSTEM_LISTEN_ON
          value: "portal:15100"
        - name: MC_ACTOR_SYSTEM
          value: "portal:15100"
        - name: ACTOR_SYSTEM_PORT_RANGE
          value: "15101-15299"
        - name: SCENARIO_GROUPS
          value: ${SCENARIO_GROUPS}
        - name: CONFIG_API_URL
          value: http://config_api:5000/v1
        - name: MGMT_API_URL
          value: http://mgmt_api:5000/v1
        - name: REDIS_URL
          value: "redis://redis:6379"
        - name: FERNET_KEY
          value: ${FERNET_KEY}
        - name: HYDRA_API_URL
          value: ${HYDRA_API_URL}
        - name: HYDRA_PUBLIC_URL
          value: ${HYDRA_INTERNAL_PUBLIC_URL}
        - name: HYDRA_CONFIG_CLIENT_ID
          value: ${HYDRA_CONFIG_CLIENT_ID}
        - name: HYDRA_CONFIG_CLIENT_SECRET
          value: ${HYDRA_CONFIG_CLIENT_SECRET}
        - name: HYDRA_CLIENT_ID
          value: ${CUSTOMER_ID}
        - name: HYDRA_CLIENT_SECRET
          value: ${HYDRA_CUSTOMER_CLIENT_SECRET}
        - name: OAUTHLIB_INSECURE_TRANSPORT
          value: "yes"
        - name: FRAME_TYPE_PROTO_MAPPING
          value: "./frame_type_proto_mapping.yaml"
        - name: MODELS_FOLDER
          value: "/training/models"
        - name: LICENSE_PUBLIC_KEY_PATH
          value: "./license_public_key.pem"
        - name: STATE_GLOBAL_TOKEN
          value: "7d9b9b94-8e2f-11e8-a84b-8c85904ee973"
        volumeMounts:
        - name: training-data
          mountPath: /training
        - name: packages
          mountPath: /packages
        - name: public-key-pem
          mountPath: /opt/quantotto/license_public_key.pem
      volumes:
      - name: training-data
        hostPath:
          path: /surveillancedata/training
      - name: packages
        hostPath:
          path: /surveillancedata/packages
      - name: public-key-pem
        hostPath:
          path: /surveillancedata/license_public_key.pem
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred

