{{ range .Values.volumes }}
apiVersion: v1
kind: {{ .kind }}
metadata:
  name: {{ .pvc.name }}
spec:
  accessModes:
    - {{ .pvc.accessMode }}
  storageClassName: {{ .pvc.className }}
  resources:
    requests:
      storage: {{ .pvc.size }}
{{ end }}
