apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: "{{ .Values.image.repository }}/nginxk8s:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 15000
        - containerPort: 15001
        resources:
          limits:
            memory: "256Mi"
            cpu: "100m"
        volumeMounts:
        - name: nginx-certs
          mountPath: /etc/nginx/certs
      volumes:
      - name: nginx-certs
        secret:
          secretName: certs
          items:
          - key: tls.key
            path: privkey.pem
          - key: tls.crt
            path: fullchain.pem
      restartPolicy: Always
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret | quote }}
