---
apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-config-{{ .Values.customer.id }}
data:
  CUSTOMER_ID: {{ .Values.customer.id | quote }}
  CUSTOMER_NAME: {{ .Values.customer.name | quote }}
  ADMIN_EMAIL: {{ .Values.customer.admin.email | quote }}
  ADMIN_LOGIN: {{ .Values.customer.admin.login | quote }}
  ADMIN_FIRST_NAME: {{ .Values.customer.admin.fname | quote }}
  ADMIN_MIDDLE_NAME: {{ .Values.customer.admin.mname | default "" | quote }}
  ADMIN_LAST_NAME: {{ .Values.customer.admin.lname | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-common-{{ .Values.customer.id }}
data:
  HYDRA_API_URL: {{ .Values.hydra.apiUrl | quote }}
  HYDRA_PUBLIC_URL: {{ .Values.hydra.internalPublicUrl | quote }}
  CONFIG_API_URL: {{ .Values.configApi.url | quote }}
  MGMT_API_URL: {{ .Values.managementApi.url | quote }}
  DATA_API_URL: {{ .Values.dataApi.url | quote }}
  REDIS_URL: {{ .Values.redis.url | quote }}
  HYDRA_CONFIG_CLIENT_ID: {{ .Values.configApi.clientId | quote }}
  HYDRA_CLIENT_ID: {{ .Values.customer.id | quote }}
  OAUTHLIB_INSECURE_TRANSPORT: "yes"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: portal-{{ .Values.customer.id }}
data:
  LICENSE_PUBLIC_KEY_PATH: {{ .Values.portal.licensePublicKeyPath | quote }}
  MODELS_FOLDER: {{ .Values.modelsFolder | quote }}
  SCENARIO_GROUPS: {{ .Values.scenarioGroups | default "" | quote }}
  ACTOR_SYSTEM_LISTEN_ON: {{ .Values.portal.asys.listenOn | quote }}
  MC_ACTOR_SYSTEM: {{ .Values.portal.asys.master | quote }}
  ACTOR_SYSTEM_PORT_RANGE: {{ .Values.portal.asys.portsRange | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: portal-files-{{ .Values.customer.id }}
data:
  license_public_key.pem:
{{ .Values.encryptionKeys.publicKey | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: real-time-data-{{ .Values.customer.id }}
data:
  SCENARIO_GROUPS: {{ .Values.scenarioGroups | default "" | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: training-scheduler-{{ .Values.customer.id }}
data:
  MODELS_FOLDER: {{ .Values.modelsFolder | quote }}
  SCENARIO_GROUPS: {{ .Values.scenarioGroups | default "" | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: triggers-runner-{{ .Values.customer.id }}
data:
  MODELS_FOLDER: {{ .Values.modelsFolder | quote }}
  SCENARIO_GROUPS: {{ .Values.scenarioGroups | default "" | quote }}
  ACTOR_SYSTEM_LISTEN_ON: {{ .Values.triggersRunner.asys.listenOn | quote }}
  MC_ACTOR_SYSTEM: {{ .Values.triggersRunner.asys.master | quote }}
  ACTOR_SYSTEM_PORT_RANGE: {{ .Values.triggersRunner.asys.portsRange | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: faces-recognizer-{{ .Values.customer.id }}
data:
  SCENARIO_GROUPS: {{ .Values.scenarioGroups | default "" | quote }}
  ACTOR_SYSTEM_LISTEN_ON: {{ .Values.facesRecognizer.asys.listenOn | quote }}
  MC_ACTOR_SYSTEM: {{ .Values.facesRecognizer.asys.master | quote }}
  ACTOR_SYSTEM_PORT_RANGE: {{ .Values.facesRecognizer.asys.portsRange | quote }}
  ARCHIVE_DOMAIN: "{{ .Values.customer.id }}.data.quantotto.io"
  H5_SERV_ENDPOINT: {{ .Values.h5serv.url | quote }}
  KNOWN_FACES_GROUP: {{ .Values.facesRecognizer.knownFacesGroup | default "" | quote }}
  FACE_CLASSIFIER_NAME:  {{ .Values.facesRecognizer.faceClassifierName | default "" | quote }}

