apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-create-customer"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      volumes:
        - name: keys
          secret:
            secretName: private-key-{{ .Values.customer.id }}
            items:
            - key: public.key
              path: public_key.pem
            - key: private.key
              path: private_key.pem
      containers:
      - name: configure-customer
        image: "{{ .Values.image.repository }}/app_base:{{ .Values.image.tag }}"
        env:
        - name: SUPER_ADMIN_SECRET
          value: "{{ .Values.encryptionKeys.superAdminSecret }}"
        - name: QDB_USER
          value: "{{ .Values.qdb.user }}"
        - name: QDB_PASSWORD
          value: "{{ .Values.qdb.password }}"
        - name: QDB_HOST
          value: "{{ .Values.qdb.host }}"
        envFrom:
        - configMapRef:
            name: app-common-{{ .Values.customer.id }}
        - configMapRef:
            name: customer-config-{{ .Values.customer.id }}
        - secretRef:
            name: common-{{ .Values.customer.id }}
        - secretRef:
            name: customer-secret-{{ .Values.customer.id }}
        command:
        - python
        - "scripts/k8s_create_customer.py"
        volumeMounts:
        - name: keys
          mountPath: /opt/quantotto/keys
        imagePullPolicy: Always
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret.name | quote }}